brand = "fan"
model = "generic"
device_type = "fan"
carrier_frequency = 38000
protocol = "nec"

[commands.power]
type = "nec"
address = "0x7F80"
command = "0xE51A"

[commands.mute]
type = "nec"
address = "0x7F80"
command = "0xE11E"

[commands.speed]
type = "nec"
address = "0x7F80"
command = "0xFE01"

[commands.toggle_rotate]
type = "nec"
address = "0x7F80"
command = "0xFC03"
